{% set name = "meilisearch-python-async" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meilisearch_python_async-{{ version }}.tar.gz
  sha256: 4b10948a3e08b93c8c2ac05bde9bf4b286a0da8c53305ae00ba2b4347982daf2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - aiofiles >=0.7
    - camel-converter >=1.0.0
    - httpx >=0.17
    - pydantic >=1.8
    - pyjwt >=2.3.0

test:
  imports:
    - meilisearch_python_async
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sanders41/meilisearch-python-sdk
  summary: A Python async client for the Meilisearch API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
